import { Injectable, Logger } from '@nestjs/common';
import { PrismaService } from '../../common/prisma/prisma.service';
import { ConfigService } from '@nestjs/config';
import { RecursiveCharacterTextSplitter } from '@langchain/textsplitters';
import { PDFLoader } from '@langchain/community/document_loaders/fs/pdf';
import { DocxLoader } from '@langchain/community/document_loaders/fs/docx';
import OpenAI from 'openai';
import * as fs from 'fs';

@Injectable()
export class RagService {
  private readonly logger = new Logger(RagService.name);
  private openrouter?: OpenAI;
  private model: string;
  private embeddingModel: string;

  constructor(
    private prisma: PrismaService,
    private config: ConfigService,
  ) {
    const apiKey = this.config.get<string>('OPENROUTER_API_KEY') ?? '';
    this.model =
      this.config.get<string>('OPENROUTER_MODEL') ?? 'openai/gpt-4o-mini';
    this.embeddingModel =
      this.config.get<string>('OPENROUTER_EMBEDDING_MODEL') ??
      'text-embedding-3-small';

    if (apiKey) {
      this.openrouter = new OpenAI({
        apiKey,
        baseURL: 'https://openrouter.ai/api/v1',
        defaultHeaders: {
          'HTTP-Referer': 'https://library-rag.app',
          'X-Title': 'Library RAG',
        },
      });
    }
  }

  // ─── EMBEDDING (remote via OpenRouter, like BashaAI) ──────────────────────
  // Embeddings are generated by a hosted API instead of a local ONNX model.
  // This removes the CPU-bound warm-up and per-request inference that made the
  // first (and sometimes every) request slow or fail on low-memory machines.

  /** Embed a batch of texts in a single API call. Retries transient failures. */
  private async embedBatch(texts: string[]): Promise<number[][]> {
    if (!this.openrouter) {
      throw new Error('OpenRouter API key is not configured.');
    }

    const input = texts.map((t) => t.replace(/\n/g, ' ').trim() || ' ');

    const maxAttempts = 3;
    let lastErr: unknown;
    for (let attempt = 1; attempt <= maxAttempts; attempt++) {
      try {
        const response = await this.openrouter.embeddings.create({
          model: this.embeddingModel,
          input,
        });
        // Preserve input order (API returns objects with an `index`).
        return response.data
          .sort((a, b) => a.index - b.index)
          .map((d) => d.embedding as number[]);
      } catch (err) {
        lastErr = err;
        this.logger.warn(
          `Embedding attempt ${attempt}/${maxAttempts} failed: ${(err as Error).message}`,
        );
        if (attempt < maxAttempts) {
          await new Promise((r) => setTimeout(r, 500 * attempt));
        }
      }
    }
    throw lastErr;
  }

  private async embedText(text: string): Promise<number[]> {
    const [vector] = await this.embedBatch([text]);
    return vector;
  }

  // ─── INDEXING ─────────────────────────────────────────────────────────────

  async indexDocument(documentId: string, filePath: string, mimetype: string): Promise<void> {
    this.logger.log(`Starting indexing for document ${documentId}`);
    try {
      // 1. Extract text
      const rawText = await this.extractText(filePath, mimetype);
      if (!rawText || rawText.length < 10) {
        await this.updateDocStatus(documentId, 'failed', 0);
        return;
      }

      // 2. Chunk text
      const splitter = new RecursiveCharacterTextSplitter({
        chunkSize: 1000,
        chunkOverlap: 200,
      });
      const chunks = await splitter.splitText(rawText);
      this.logger.log(`Split into ${chunks.length} chunks`);

      // 3. Generate embeddings in batches and store.
      // Batching keeps indexing fast: one API round-trip per BATCH_SIZE chunks
      // instead of one per chunk.
      const BATCH_SIZE = 32;
      let saved = 0;
      for (let i = 0; i < chunks.length; i += BATCH_SIZE) {
        const batch = chunks.slice(i, i + BATCH_SIZE);
        const vectors = await this.embedBatch(batch);

        for (let j = 0; j < batch.length; j++) {
          await this.prisma.$executeRawUnsafe(
            `INSERT INTO "DocumentChunk" (id, "documentId", content, embedding)
             VALUES (gen_random_uuid(), $1, $2, $3::vector)`,
            documentId,
            batch[j],
            JSON.stringify(vectors[j]),
          );
          saved++;
        }
        this.logger.log(`Indexed ${saved}/${chunks.length} chunks`);
      }

      await this.updateDocStatus(documentId, 'indexed', saved);
      this.logger.log(`Indexed ${saved} chunks for document ${documentId}`);
    } catch (err) {
      this.logger.error(`Indexing failed for ${documentId}: ${err.message}`, err.stack);
      await this.updateDocStatus(documentId, 'failed', 0);
    }
  }

  // ─── CHAT (via OpenRouter) ────────────────────────────────────────────────

  async chat(
    question: string,
    history?: Array<{ role: string; content: string }>,
  ): Promise<{ answer: string; sources: unknown[] }> {
    const dataContext = await this.getDataContext();

    if (!this.openrouter) {
      return {
        answer:
          'The library assistant is not configured with an OpenRouter API key yet. I can still provide the non-confidential library snapshot, but AI generation is unavailable until the key is configured.',
        sources: [],
      };
    }

    // 1. Embed the user question via OpenRouter
    const queryVector = await this.embedText(question);

    // 2. Similarity search in pgvector (top 5 chunks)
    let results: Record<string, unknown>[];
    try {
      results = await this.prisma.$queryRawUnsafe(
        `SELECT dc.id, dc.content, dc."documentId", dc.page,
                1 - (dc.embedding <=> $1::vector) AS score,
                d.name AS "documentName"
         FROM "DocumentChunk" dc
         JOIN "Document" d ON dc."documentId" = d.id
         WHERE dc.embedding IS NOT NULL
         ORDER BY dc.embedding <=> $1::vector
         LIMIT 5`,
        JSON.stringify(queryVector),
      );
    } catch (err) {
      // Old chunks embedded with the previous local model have a different
      // vector dimension and cannot be compared — they must be re-indexed.
      if (String((err as Error).message).includes('different vector dimensions')) {
        this.logger.error(
          'Stale embeddings detected (dimension mismatch). Delete old chunks and re-upload documents.',
        );
        return {
          answer:
            'The document index is outdated and needs to be rebuilt. Please re-upload the library documents.',
          sources: [],
        };
      }
      throw err;
    }

    if (!results || results.length === 0) {
      return {
        answer:
          "I couldn't find relevant information in the library documents. Please try rephrasing your question.",
        sources: [],
      };
    }

    // 3. Build context from retrieved chunks
    const context = results
      .map((r, i) => `[${i + 1}] ${r.content}`)
      .join('\n\n');

    const dataSnapshot = this.buildDataContext(dataContext);

    // 4. Generate answer via OpenRouter
    const prompt = this.buildPrompt(question, dataSnapshot, context, history ?? []);

    const completion = await this.openrouter.chat.completions.create({
      model: this.model,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.2,
      max_tokens: 1024,
    });

    const choiceMsg = completion.choices[0]?.message;
    const answer =
      choiceMsg?.content ||
      (choiceMsg as any)?.reasoning ||
      'No answer returned.';

    const sources = results.map((r) => ({
      documentId: r.documentId,
      documentName: r.documentName,
      snippet: String(r.content).substring(0, 200) + '...',
      page: r.page,
      score: parseFloat(String(r.score)),
    }));

    return { answer, sources };
  }

  // ─── HELPERS ──────────────────────────────────────────────────────────────

  private buildPrompt(
    question: string,
    dataSnapshot: string,
    context: string,
    history: Array<{ role: string; content: string }>,
  ) {
    const historyBlock = history.length
      ? `\nConversation history:\n${history
          .map((entry) => `${entry.role}: ${entry.content}`)
          .join('\n')}`
      : '';

    return `You are a helpful library assistant. Answer the question using the provided library documents, the non-confidential library data snapshot, and the recent conversation history when relevant. If the context does not contain the answer, say so clearly. Do not reveal private member details such as names, emails, addresses, or other sensitive personal information.${historyBlock}

Library data snapshot:
${dataSnapshot}

Document context:
${context}

Question: ${question}

Answer:`;
  }

  private buildDataContext(data: {
    totalBooks: number;
    availableCopies: number;
    activeMembers: number;
    memberStatusBreakdown: Array<{ status: string; _count: { id: number } }>;
    recentBooks: Array<{
      title: string;
      author: string;
      description?: string | null;
      availableCopies: number;
      totalCopies: number;
      shelfLocation?: string | null;
    }>;
  }) {
    const statusSummary = data.memberStatusBreakdown
      .map((item) => `${item.status}: ${item._count.id}`)
      .join(', ');

    const bookLines = data.recentBooks
      .slice(0, 5)
      .map((book) => {
        const description = book.description?.trim()
          ? ` | description: ${book.description.trim()}`
          : '';
        return `- ${book.title} by ${book.author} (${book.availableCopies}/${book.totalCopies} available; shelf: ${book.shelfLocation || 'unknown'})${description}`;
      })
      .join('\n');

    return [
      `Books in catalog: ${data.totalBooks}`,
      `Available copies: ${data.availableCopies}`,
      `Active members: ${data.activeMembers}`,
      `Member status breakdown: ${statusSummary}`,
      'Recently available or notable books:',
      bookLines || '- No recent book data available',
    ].join('\n');
  }

  private async getDataContext() {
    const [totalBooks, availableCopies, activeMembers, memberStatusBreakdown, recentBooks] =
      await Promise.all([
        this.prisma.book.count(),
        this.prisma.book.aggregate({ _sum: { availableCopies: true } }),
        this.prisma.member.count({ where: { status: 'active' } }),
        this.prisma.member.groupBy({
          by: ['status'],
          _count: { id: true },
        }),
        this.prisma.book.findMany({
          take: 5,
          orderBy: { borrowCount: 'desc' },
          select: {
            title: true,
            description: true,
            author: { select: { name: true } },
            availableCopies: true,
            totalCopies: true,
            shelfLocation: true,
          },
        }),
      ]);

    return {
      totalBooks,
      availableCopies: availableCopies._sum.availableCopies ?? 0,
      activeMembers,
      memberStatusBreakdown,
      recentBooks: recentBooks.map((book) => ({
        title: book.title,
        author: book.author.name,
        description: book.description,
        availableCopies: book.availableCopies,
        totalCopies: book.totalCopies,
        shelfLocation: book.shelfLocation,
      })),
    };
  }

  private async extractText(filePath: string, mimetype: string): Promise<string> {
    try {
      if (mimetype === 'application/pdf') {
        const loader = new PDFLoader(filePath);
        const docs = await loader.load();
        return docs.map((d) => d.pageContent).join('\n\n');
      }

      if (
        mimetype ===
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
      ) {
        const loader = new DocxLoader(filePath);
        const docs = await loader.load();
        return docs.map((d) => d.pageContent).join('\n\n');
      }

      if (mimetype === 'text/plain') {
        return fs.readFileSync(filePath, 'utf-8');
      }

      this.logger.warn(`No text extractor for mimetype ${mimetype}`);
      return '';
    } catch (err) {
      this.logger.error(`Text extraction failed: ${err.message}`);
      return '';
    }
  }

  private async updateDocStatus(id: string, status: string, chunkCount: number) {
    await this.prisma.document.update({
      where: { id },
      data: { status, chunkCount },
    });
  }
}
